export enum CaseHistory {
  OPENED = "CASE-OPENED",
  ASSIGNED = "CASE-ASSIGNED",
  STATUS_CHANGE = "STATUS-CHANGE",
  CLOSED = "CASE-CLOSED",
  COMMENT_ADDED = "COMMENT-ADDED",
  COMMENT_EDITED = "COMMENT-EDITED",
  COMMENT_DELETED = "COMMENT-DELETED",
  DOCUMENT_UPLOADED = "DOCUMENT-UPLOADED",
  DETAILS_EDITED = "CASE-DETAILS-EDITED",
  CLIENT_EDITED = "CLIENT-DETAILS-EDITED",
  DESCRIPTION_EDITED = "DESCRIPTION-EDITED",
}
